"""refresh_tokens table for revocation (M055)

Revision ID: 0011
Revises: 0010
Create Date: 2026-09-30 00:00:00.000000

Autogenerated, then hand-reviewed and restyled (M008 standing rule).
One row per issued refresh token, keyed by the token's ``jti`` claim:

- ``user_id`` FK CASCADE: deleting a user removes their token rows.
- ``revoked_at`` NULL while active — logout/rotation flip it; a
  *presented* revoked row means the token leaked (reuse detection).
- ``expires_at`` mirrors the JWT ``exp`` so the row can be garbage-
  collected without decoding anything.
- No token material is stored — the JWT remains the credential; the
  row is only its lifecycle state.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0011"
down_revision: str | Sequence[str] | None = "0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "refresh_tokens",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "issued_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_refresh_tokens_user_id", "refresh_tokens", ["user_id"])


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("ix_refresh_tokens_user_id", table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
